---
- name: Manage Subnets
  redhat.satellite.subnet:
    name: "{{ item.name }}"
    network: "{{ item.network }}"
    mask: "{{ item.mask }}"
    gateway: "{{ item.gateway }}"
    domains: "{{ item.domains }}"
    dns_primary: "{{ item.dns_primary }}"
    dns_secondary: "{{ item.dns_secondary|default(omit) }}"
    from_ip: "{{ item.from_ip|default(omit) }}"
    to_ip: "{{ item.to_ip|default(omit) }}"
    boot_mode: "{{ item.boot_mode }}"
    tftp_proxy: "{{ item.tftp_proxy }}"
    username: "{{ sat_user }}"
    password: "{{ sat_passwd }}"
    server_url: "{{ sat_url }}"
    locations: "{{ locations }}"
    remote_execution_proxies: "{{ item.remote_execution_proxies|default(omit) }}"
  loop: "{{ subnets }}"
  tags: subnets
