---
- name: "Enable Red Hat Kickstart repositories"
  redhat.satellite.repository_set:
    username: "{{ sat_user }}"
    password: "{{ sat_passwd }}"
    server_url: "{{ sat_url }}"
    organization: "{{ organization }}"
    label: "{{ item.label }}"
    state: enabled
    repositories: "{{ item.repos }}"
  loop: "{{ redhat_kickstart_repos }}"
  tags: enable_redhat_kickstart_repos

- name: "Enable Red Hat OS repositories"
  redhat.satellite.repository_set:
    username: "{{ sat_user }}"
    password: "{{ sat_passwd }}"
    server_url: "{{ sat_url }}"
    organization: "{{ organization }}"
    label: "{{ item.label }}"
    state: enabled
    repositories: "{{ item.repos }}"
  loop: "{{ redhat_os_repos }}"
  tags: enable_redhat_os_repos
