---
- name: "Check if Manifest is already pulled down"
  stat:
    path: '"{{ manifest_path }}"/satellite_manifest.zip'
  register: stat_result

- name: "Manifest | Pull down manifest"
  get_url:
    url: https://subscription.rhsm.redhat.com/subscription/consumers/{{ satellite_manifest_uuid }}/export
    username: "{{ sat_user }}"
    password: "{{ sat_passwd }}"
    dest: '"{{ manifest_path }}"/satellite_manifest.zip'
    validate_certs: true
    timeout: 300
  when: not stat_result.stat.exists

- name: "Manifest upload"
  redhat.satellite.subscription_manifest:
    username: "{{ sat_user }}"
    password: "{{ sat_passwd }}"
    server_url: "https://{{ ansible_fqdn }}"
    organization: "{{ organization }}"
    state: present
    manifest_path: '"{{ manifest_path }}"/satellite_manifest.zip'
  when: not stat_result.stat.exists
  tags: manifest
